### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/user/list
#Content-Type: application/json

###
POST http://localhost:8080/user/user
Content-Type: application/json

{
   "id": 34321,
  "name": "testSample123123"
}

###

PUT http://localhost:8080/user/user/#{id}
Content-Type: application/json

{
    "id" : 77777,
    "name" : "test1"
}
