### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/user/list
#Content-Type: application/json

###
POST http://localhost:8080/user/user
Content-Type: application/json

{
   "id": 34321,
  "name": "testSample123123"
}

###

PUT http://localhost:8080/user/user/#{id}
Content-Type: application/json

{
    "id" : 77777,
    "name" : "test1"
}

###
GET http://localhost:8080/page-placement/top
Content-Type: application/json

###
POST http://localhost:8080/favorite?popupNo=1

###
GET http://localhost:8080/popup-store/random

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "user10",
  "password": "pass10"
}

###
GET http://localhost:8080/auth/refresh

###
200 OK
{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InVzZXIxMCIsInR5cGUiOiJNRU1CRVIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2MzAxOTM3NSwiZXhwIjoxNzYzMDIxMTc1fQ.V4F2gAjISmamNJtTgjFzRKqhh6pOdbkdIIQzjVQlUU8"
}